const express = require('express');
const router = express.Router();

// Route for Swagger documentation
// This route serves the API documentation generated by Swagger,
// allowing developers to understand the API endpoints and their usage.
router.use('/', require('./swagger'));

// Cart Item Routes
// This route manages all operations related to cart items,
// including adding, updating, retrieving, and deleting items in the cart.
router.use('/cartitems', require('./cartItemRoutes'));

// Category Routes
// This route handles all requests related to product categories,
// such as creating, retrieving, updating, and deleting categories.
router.use('/categories', require('./categoryRoutes'));

// Order Item Routes
// This route manages all operations related to order items,
// including adding, updating, retrieving, and deleting items in orders.
router.use('/orderitems', require('./orderItemRoutes'));

// Order Routes
// This route facilitates order management, including placing orders,
// viewing order history, updating order status, and handling returns.
router.use('/orders', require('./orderRoutes'));

// Payment Routes
// This route manages payment processing for orders, including
// creating, retrieving, updating, and deleting payment records.
router.use('/payments', require('./paymentRoutes'));

// Product Routes
// This route manages all product-related operations, such as
// listing products, adding new products, updating product details,
// and deleting products from the catalog.
router.use('/products', require('./productRoutes'));

// Review Routes
// This route allows users to submit ratings and reviews for products,
// as well as retrieve ratings for specific products to enhance user
// decision-making.
router.use('/reviews', require('./reviewRoutes'));

// Shopping Cart Routes
// This route handles all requests related to shopping carts,
// including creating, updating, retrieving, and deleting shopping carts.
router.use('/shoppingcarts', require('./shoppingCartRoutes'));

// Seller Routes
// This route handles all requests related to seller profiles, including
// viewing, adding, updating, and deleting seller information.
router.use('/sellers', require('./sellerRoutes'));

// User Routes
// This route encompasses all user-related functionality, including
// user registration, authentication, profile management, and
// retrieving user information.
router.use('/users', require('./userRoutes'));

// Export the router to be used in the main application
module.exports = router;

