CREATE TABLE "Users" (
	"user_id" INTEGER NOT NULL UNIQUE GENERATED BY DEFAULT AS IDENTITY,
	"name" VARCHAR(255),
	"email" VARCHAR(255),
	"password" VARCHAR(255),
	"user_type" UUID,
	"join_date" DATE,
	"profile_picture" TEXT(65535),
	"bio" TEXT(65535),
	"address" VARCHAR(255),
	PRIMARY KEY("user_id")
);


CREATE TABLE "Products" (
	"product_id" INTEGER NOT NULL UNIQUE GENERATED BY DEFAULT AS IDENTITY,
	"seller_id" INTEGER,
	"title" VARCHAR(255),
	"description" TEXT(65535),
	"price" NUMERIC,
	"stock_quantity" NUMERIC,
	"category_id" INTEGER,
	"created_at" DATE,
	"updated_at" DATE,
	"image_url" TEXT(65535),
	"status" UUID,
	PRIMARY KEY("product_id")
);


CREATE TABLE "Categories" (
	"category_id" INTEGER NOT NULL UNIQUE GENERATED BY DEFAULT AS IDENTITY,
	"name" VARCHAR(255),
	"description" TEXT(65535),
	PRIMARY KEY("category_id")
);


CREATE TABLE "Orders" (
	"order_id" INTEGER NOT NULL UNIQUE GENERATED BY DEFAULT AS IDENTITY,
	"user_id" INTEGER,
	"total_price" NUMERIC,
	"order_date" DATE,
	"status" UUID,
	"shipping_address" VARCHAR(255),
	PRIMARY KEY("order_id")
);


CREATE TABLE "Order_Items" (
	"order_item_id" INTEGER NOT NULL UNIQUE GENERATED BY DEFAULT AS IDENTITY,
	"order_id" INTEGER,
	"product_id" INTEGER,
	"quantity" NUMERIC,
	"price" NUMERIC,
	PRIMARY KEY("order_item_id")
);


CREATE TABLE "Reviews" (
	"review_id" INTEGER NOT NULL UNIQUE GENERATED BY DEFAULT AS IDENTITY,
	"user_id" INTEGER,
	"product_id" INTEGER,
	"rating" SMALLINT,
	"comment" VARCHAR(255),
	"created_at" DATE,
	PRIMARY KEY("review_id")
);


CREATE TABLE "Payments" (
	"payment_id" INTEGER NOT NULL UNIQUE GENERATED BY DEFAULT AS IDENTITY,
	"order_id" INTEGER,
	"payment_date" DATE,
	"payment_method" VARCHAR(255),
	"payment_status" VARCHAR(255),
	PRIMARY KEY("payment_id")
);


CREATE TABLE "Shopping_Cart" (
	"cart_id" INTEGER NOT NULL UNIQUE GENERATED BY DEFAULT AS IDENTITY,
	"customer_id" INTEGER,
	PRIMARY KEY("cart_id")
);


CREATE TABLE "Cart_Items" (
	"cart_item_id" INTEGER NOT NULL UNIQUE GENERATED BY DEFAULT AS IDENTITY,
	"cart_id" INTEGER,
	"product_id" INTEGER,
	"quantity" INTEGER,
	PRIMARY KEY("cart_item_id")
);


ALTER TABLE "Categories"
ADD FOREIGN KEY("category_id") REFERENCES "Products"("category_id")
ON UPDATE NO ACTION ON DELETE NO ACTION;
ALTER TABLE "Order_Items"
ADD FOREIGN KEY("order_id") REFERENCES "Orders"("order_id")
ON UPDATE NO ACTION ON DELETE NO ACTION;
ALTER TABLE "Order_Items"
ADD FOREIGN KEY("product_id") REFERENCES "Products"("product_id")
ON UPDATE NO ACTION ON DELETE NO ACTION;
ALTER TABLE "Cart_Items"
ADD FOREIGN KEY("cart_id") REFERENCES "Shopping_Cart"("cart_id")
ON UPDATE NO ACTION ON DELETE NO ACTION;
ALTER TABLE "Cart_Items"
ADD FOREIGN KEY("product_id") REFERENCES "Products"("product_id")
ON UPDATE NO ACTION ON DELETE NO ACTION;
ALTER TABLE "Payments"
ADD FOREIGN KEY("order_id") REFERENCES "Orders"("order_id")
ON UPDATE NO ACTION ON DELETE NO ACTION;
ALTER TABLE "Reviews"
ADD FOREIGN KEY("product_id") REFERENCES "Products"("product_id")
ON UPDATE NO ACTION ON DELETE NO ACTION;
ALTER TABLE "Orders"
ADD FOREIGN KEY("user_id") REFERENCES "Users"("user_id")
ON UPDATE NO ACTION ON DELETE NO ACTION;